core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
]

fruit_sell/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("core.urls")),
    path('fruits/',include("fruit.urls")),
    path('user/', include('users.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('signup/',views.UserRegistrationView.as_view(), name='signup'),
    path('login/',views.UserLoginView.as_view(), name='login'),
    path('logout/',views.UserLogoutView.as_view(), name='logout'),
    path('profile/',views.Profile.as_view(), name='profile'),
    path('update_profile/',views.UserAccountUpdateView.as_view(), name='update_profile'),
    path('change_password/', views.ChangePasswordView.as_view(), name='change_pass'),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"), name='password_reset_complete'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserAccount(models.Model):
    user = models.OneToOneField(User, related_name='account', on_delete=models.CASCADE)
    profile_image = models.ImageField(upload_to='./profile-images/uploads/', blank=True, null=True)
    gender = models.CharField(max_length=10)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"

core/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label="Write your full Name ",required=True,  widget = forms.TextInput(attrs={'class': 'form-control', 'id':'text-area', 'placeholder':'Enter your full name'}))
    email = forms.EmailField(label="Write your email",required=False, widget = forms.TextInput(attrs={'class': 'form-control', 'id':'text-area', 'placeholder':'Enter your email'}))
    feedback = forms.CharField(label="Write your feedback ",required=True, widget = forms.Textarea(attrs={'class': 'form-control', 'id':'text-area', 'placeholder':'Write your feedback'}))

         

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import UserAccount

GENDER_TYPE = (
    ('Male', 'Male'),
    ('Female', 'Female'),
)
class RegistrationForm(UserCreationForm):
    profile_image = forms.ImageField(required=False)
    gender = forms.ChoiceField(choices=GENDER_TYPE)
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email','profile_image','gender','password1', 'password2' ]
    
    def save(self, commit=True):
        account_user = super().save(commit=False)
        if commit == True:
            account_user.save()
            profile_image = self.cleaned_data.get('profile_image')
            gender = self.cleaned_data.get('gender')
        
        UserAccount.objects.create(
            user = account_user,
            profile_image = profile_image,
            gender = gender,
        )
    
        return account_user


class EditProfile(forms.ModelForm):
    profile_image = forms.ImageField(required=False)
    gender = forms.ChoiceField(choices=GENDER_TYPE)

    class Meta:
        model = User
        fields = ['first_name', 'last_name','email']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        if self.instance:
            try:
                user_account = self.instance.account
            except UserAccount.DoesNotExist:
                user_account = None

            if user_account:
                self.fields['profile_image'].initial = user_account.profile_image
                self.fields['gender'].initial = user_account.gender

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()

            user_account, created = UserAccount.objects.get_or_create(user=user)

            user_account.profile_image = self.cleaned_data['profile_image']
            user_account.gender = self.cleaned_data['gender']
            
            user_account.save()

        return user

users/views.py
from django.shortcuts import render, redirect

from order.models import Order
from . import forms
from django.contrib import messages
from django.views.generic import FormView, View
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LoginView
from django.contrib.auth import login, logout, update_session_auth_hash
from django.urls import reverse_lazy
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


# Create your views here.
class UserRegistrationView(FormView):
    template_name = 'signup.html'
    form_class = forms.RegistrationForm
    success_url = reverse_lazy('home')
    
    def form_valid(self,form):
        user = form.save()
        login(self.request, user)
        messages.success(self.request, 'Registered successfully! You are logged in now')
        return super().form_valid(form)

class UserLoginView(LoginView):
    template_name = 'login.html'
    def get_success_url(self):
        return reverse_lazy('home')
    def form_valid(self, form):
        messages.success(self.request, 'Logged In Successfully')
        return super().form_valid(form)
    def form_invalid(self, form):
        print(form.cleaned_data)
        messages.warning(self.request, 'User Information is incorrect')
        return super().form_invalid(form)


@method_decorator(login_required, name='dispatch')
class UserLogoutView(View):
    def get(self, request):
        messages.success(self.request, 'Successfully logged out!')
        logout(request)
        return redirect('login')

@method_decorator(login_required, name='dispatch')    
class Profile(TemplateView):
    template_name = 'profile.html'
    def get(self, request):
         orders = Order.objects.filter(user=request.user, ordered=True, removed_from_view=False).order_by('-timestamp')
         return render(request, self.template_name, {'orders': orders})

@method_decorator(login_required, name='dispatch')
class UserAccountUpdateView(View):
    template_name = 'update_profile.html'

    def get(self, request):
        form = forms.EditProfile(instance=request.user)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = forms.EditProfile(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(self.request, 'Profile updated successfully!')
            return redirect('profile')
        return render(request, self.template_name, {'form': form})

@method_decorator(login_required, name='dispatch')
class ChangePasswordView(TemplateView):
    template_name = 'change_pass.html'

    def post(self, request, *args, **kwargs):
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('update_profile')
        else:
            for field in form:
                for error in field.errors:
                    messages.warning(request, f"{field.label}: {error}")
                    return self.render_to_response(self.get_context_data(form=form))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = PasswordChangeForm(self.request.user)
        return context

    
   

    

users/templates/change_pass.html
<!-- change_password.html -->
{% extends 'base.html' %}
{% block head_title %}Update Password{% endblock %}

{% block content %}
<div class="form d-flex justify-content-center align-items-center mt-2">
    <div class="d-flex flex-column justify-content-center p-5 rounded rounded shadow-lg" style="width: 640px;  background: #e9e8e8;">
        <div class="text-center fw-bold mb-3 fs-1">
            <header>Update your password</header>
        </div>
        <form style="width: 440px;" class="mx-auto" enctype="multipart/form-data" action="" method="post">
            {% csrf_token %}
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                <strong>Error!</strong> Please correct the following errors:
                <ul>
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% endfor %}
                </ul>
            </div>
            {% endif %}
            <div class="input-box">
                <label for="id_old_password">Old Password:</label>
                <input type="password" id="id_old_password" class="input-field" placeholder="Enter your old password" name="old_password" autocomplete="off" required>
                {% for err in form.old_password.errors %}
                    <small class="text-dnager ms-2">{{ err }}</small>
                {% endfor %}
            </div>
            <div class="input-box">
                <label for="id_new_password1">New Password:</label>
                <input type="password" id="id_new_password1" class="input-field" placeholder="Enter your new password" name="new_password1" autocomplete="off" required>
                {% for err in form.new_password1.errors %}
                    <small class="text-dnager ms-2">{{ err }}</small>
                {% endfor %}
            </div>
            <div class="input-box">
                <label for="id_new_password2">Confirm New Password:</label>
                <input type="password" id="id_new_password2" class="input-field" placeholder="Re-enter your new password" name="new_password2" autocomplete="off" required>
                {% for err in form.new_password2.errors %}
                    <small class="text-dnager ms-2">{{ err }}</small>
                {% endfor %}
            </div>
            <small class="ps-2"><a href="{% url 'reset_password' %}">Forgot Password?</a></small><br><br>
            <div>
                <input class="btn btn-outline-dark w-100 p-2 fw-bold" type="submit" value="Update Password">
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/login.html
<!-- login.html -->
{% extends 'base.html' %}
{% block head_title %}Login{% endblock %}
{% block content %}
<div class="form d-flex justify-content-center align-items-center mt-2">
    <div class="d-flex flex-column justify-content-center p-5 rounded rounded shadow-lg" style="width: 640px; background: #e0dddd;">
        <div class="text-center fw-bold mb-5 fs-1">
            <header>Login</header>
        </div>
        <form style="width: 440px;" class="mx-auto" enctype="multipart/form-data" action="" method="post">
            {% csrf_token %}
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                <strong>Error!</strong> Please correct the following errors:
                <ul>
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <li>{{ field }}: {{ error }}</li>
                    {% endfor %}
                {% endfor %}
                </ul>
            </div>
            {% endif %}
            <!-- Username -->
            <div class="input-box">
                <label for="id_username">Username:</label>
                <input type="text" id="id_username" class="input-field" placeholder="Enter your username" name="username" autocomplete="off" required>
            </div>
            <!-- Password -->
            <div class="input-box">
                <label for="id_password">Password:</label>
                <input type="password" id="id_password" class="input-field" placeholder="Enter your password" name="password" autocomplete="off" required>
            </div>
            <!-- Forgot Password -->
            <small class="ps-2"><a href="{% url 'reset_password' %}">Forgot Password?</a></small><br><br>
            <!-- Submit Button -->
            <div>
                <input class="btn btn-outline-dark w-100 p-2 fw-bold" type="submit" value="Login">
            </div>
        </form>
        <!-- Signup Link -->
        <div class="mt-3">
            <p class="text-center">Don't have an account? <a href="{% url 'signup' %}">Sign Up now!</a></p>
        </div>
    </div>
</div>
{% endblock %}

users/templates/password_reset.html
<!-- login.html -->
{% extends 'base.html' %}
{% block head_title %}Password Reset{% endblock %}
{% block content %}
<div class="form d-flex justify-content-center align-items-center mt-2">
    <div class="d-flex flex-column justify-content-center p-5 rounded rounded shadow-lg" style="width: 640px; background: #e0dddd;">
        <div class="text-center fw-bold mb-5 fs-1">
            <header>Reset your password!</header>
        </div>
        <form style="width: 440px;" class="mx-auto" enctype="multipart/form-data" action="" method="post">
            {% csrf_token %}
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                <strong>Error!</strong> Please correct the following errors:
                <ul>
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <li>{{ field }}: {{ error }}</li>
                    {% endfor %}
                {% endfor %}
                </ul>
            </div>
            {% endif %}
            <!-- Username -->
            <div class="input-box">
                <label for="id_email">Email:</label>
                <input type="email" id="id_email" class="input-field" placeholder="Enter your email" name="email" autocomplete="off" required>
            </div>
            <div class="mt-3">
                <input class="btn btn-outline-dark w-100 p-2 fw-bold" type="submit" value="Reset password">
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/password_reset_complete.html
<!-- login.html -->
{% extends 'base.html' %}
{% block head_title %}Password Reset{% endblock %}
{% block content %}
<div class="form d-flex justify-content-center align-items-center mt-2">
    <div class="d-flex flex-column justify-content-center p-5 rounded rounded shadow-lg" style="width: 640px; background: #e0dddd;">
        <div class="text-center fw-bold mb-5 fs-1">
            <header>Reset your password!</header>
        </div>
        <p>Your new password has been set. You may go ahead and log in now. <br><a href="{% url 'login' %}">Login now!</a></p>
        
    </div>
</div>
{% endblock %}

users/templates/password_reset_form.html
<!-- change_password.html -->
{% extends 'base.html' %}
{% block head_title %}Set Password{% endblock %}

{% block content %}
<div class="form d-flex justify-content-center align-items-center mt-2">
    <div class="d-flex flex-column justify-content-center p-5 rounded rounded shadow-lg" style="width: 640px;  background: #e9e8e8;">
        <div class="text-center fw-bold mb-3 fs-1">
            <header>Set new password</header>
        </div>
        <form style="width: 440px;" class="mx-auto" enctype="multipart/form-data" action="" method="post">
            {% csrf_token %}
            <!-- Display form errors -->
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                <strong>Error!</strong> Please correct the following errors:
                <ul>
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% endfor %}
                </ul>
            </div>
            {% endif %}
            <!-- End of form errors -->

            <div class="input-box">
                <label for="id_new_password1">New Password:</label>
                <input type="password" id="id_new_password1" class="input-field" placeholder="Enter your new password" name="new_password1" autocomplete="off" required>
            </div>
            <div class="input-box">
                <label for="id_new_password2">Confirm New Password:</label>
                <input type="password" id="id_new_password2" class="input-field" placeholder="Re-enter your new password" name="new_password2" autocomplete="off" required>
            </div>
            <div class="mt-4">
                <input class="btn btn-outline-dark w-100 p-2 fw-bold" type="submit" value="Change Password">
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/password_reset_sent.html
<!-- login.html -->
{% extends 'base.html' %}
{% block head_title %}Password Reset{% endblock %}
{% block content %}
<div class="form d-flex justify-content-center align-items-center mt-2">
    <div class="d-flex flex-column justify-content-center p-5 rounded rounded shadow-lg" style="width: 640px; background: #e0dddd;">
        <div class="text-center fw-bold mb-5 fs-1">
            <header>Reset your password!</header>
        </div>
        <p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly. <br>

            If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>
    </div>
</div>
{% endblock %}

users/templates/profile.html
{% extends 'base.html' %}
{% block head_title %}Profile{% endblock %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<div class="container mx-auto d-flex justify-content-between">
  <div class="text-center rounded rounded-4 shadow-lg p-3 fw-bold mt-4" style="max-width: 300px; height:93vh" >
    {% if request.user.account.profile_image %}
    <img class="w-75 rounded-4 shadow-lg" src="{{request.user.account.profile_image.url}}" class="img-fluid rounded-start" alt="...">
    {% else %}
    <img class="w-75 rounded-4 shadow-lg" src="{% static './images/profile.png' %}" class="img-fluid rounded-start"
      alt="...">
    {% endif %}
    <br><br>
    <span class="fs-2">{{request.user.first_name}} {{request.user.last_name}}</span><br><br>
    
    <a class="btn btn-primary" style="display:block"  href="{% url 'update_profile' %}">Edit Profile</a>
  </div>
  <div class="container mx-auto text-center">
    <p style="margin: 20px 0px 20px 0px;" class="text-center fw-bold p-3 rounded fs-5"><span style="padding:10px" class="alert alert-danger">Your Orders</span>
    </p>
    {% if orders %}
    <table style="margin-bottom: 200px;" class="table table-striped border border-3 shadow">
      <thead>
        <tr>
          <th scope="col">Order Id</th>
          <th scope="col">Ordered Items</th>
          <th scope="col">Total Cost</th>
          <th scope="col">Payment Method</th>
          <th scope="col">Order Status</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for order in orders %}
        <tr>
          <td>
            {{ order.orderId }}
          </td>
          <td>
            <ul style="padding: 0;">
              {% for item in order.order_items.all %}
                  <li><a style="text-decoration: none;" href="{% url 'details' id=item.item.id %}">{{ item.item.name }}-{{ item.item.unit }}</a> x {{ item.quantity }}</li>
              {% endfor %}
          </ul>
          </td>
          
          <td>{{ order.get_totals }}৳</td>
          <td>{{ order.payment_method }}</td>
          {% if order.order_status == 'Cancelled' %}
          <td class="text-danger">{{ order.order_status }}</td>
          {% elif order.order_status == 'Delivered' %}
          <td class="text-success">{{ order.order_status }}</td>
          {% else %}
          <td class="text-primary">{{ order.order_status }}</td>
          {% endif %}          
          {% if order.cancelled == False and order.order_status != 'Delivered' %}
          <td><a href="{% url 'cancel-order' order.id %}" title="Cancel this order" class="btn btn-danger manage_order_btn"> Cancel Order </a></td>
          {% else %}
          <td><a href="{% url 'remove-order' order.id %}" title="Remove this record" class="btn btn-secondary manage_order_btn"> Remove </a></td>
          {% endif %}
        </tr>
        {% endfor %}
        {% else %}
        <h4 class="text-center text-secondary" style="margin-top: 100px;">You don't have any orders!</h4>
        {% endif %}
      </tbody>
    </table>
  </div>

{% endblock %}

users/templates/signup.html
<!-- sign_up.html -->
{% extends 'base.html' %}
{% block head_title %}Signup{% endblock %}
{% block content %}
<div class="form d-flex justify-content-center align-items-center my-2">
    <div class="d-flex flex-column justify-content-center p-5 rounded rounded shadow-lg" style="width: 640px;  background: #e9e8e8;">
        <div class="text-center fw-bold mb-3 fs-1">
            <header>Sign up</header>
        </div>
        <form enctype="multipart/form-data" action="" method="post">
            {% csrf_token %}
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                <strong>Error!</strong> Please correct the following errors:
                <ul>
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <li>{{ field }}: {{ error }}</li>
                    {% endfor %}
                {% endfor %}
                </ul>
            </div>
            {% endif %}
            <!-- Username -->
            <div class="input-box">
                <label for="id_username">Username:</label>
                <input type="text" id="id_username" class="input-field" placeholder="Enter your username" name="username" autocomplete="off" required>
            </div>
            <!-- First Name and Last Name -->
            <div class="d-lg-flex justify-content-between">
                <div style="width: 47.5%;" class="input-box">
                    <label for="id_first_name">First Name:</label>
                    <input type="text" id="id_first_name" class="input-field" placeholder="Enter your first name" name="first_name" autocomplete="off" required>
                </div>
                <div style="width: 47.5%;" class="input-box">
                    <label for="id_last_name">Last Name:</label>
                    <input type="text" id="id_last_name" class="input-field" placeholder="Enter your last name" name="last_name" autocomplete="off" required>
                </div>
            </div>
            <!-- Email -->
            <div class="input-box">
                <label for="id_email">Email:</label>
                <input type="email" id="id_email" class="input-field" placeholder="Enter your email" name="email" autocomplete="off" required>
            </div>
            <!-- Profile Image -->
            <img id="previewImage" class="uploaded-image" src="#" alt="Preview Image" style="display: none;">
            <div class="d-flex justify-content-between">
                <div style="width: 47.5%;" class="input-box">
                    <label for="uploadImage">Profile Image:</label>
                    <input type="file" id="uploadImage" class="input-field" name="profile_image" onchange="displayImage()">
                    <label class="up-image-label overflow-hidden" for="uploadImage">
                        <i class="fa-solid fa-upload me-2"></i>
                        <span class="image-label">Upload Profile Image</span>
                    </label>
                </div>
                <!-- Gender -->
                <div style="width: 47.5%;" class="input-box">
                    <label for="id_gender">Gender:</label>
                    <select id="id_gender" class="input-field" name="gender" required>
                        <option class="text-secondary" hidden>Select your gender</option>
                        <option value="Male">Male</option>
                        <option value="Female">Female</option>
                    </select>
                </div>
            </div>
            <!-- Password -->
            <div class="input-box">
                <label for="id_password1">Password:</label>
                <input type="password" id="id_password1" class="input-field" placeholder="Enter a password" name="password1" autocomplete="off" required>
            </div>
            <!-- Confirm Password -->
            <div class="input-box">
                <label for="id_password2">Re-type Password:</label>
                <input type="password" id="id_password2" class="input-field" placeholder="Re-type password" name="password2" autocomplete="off" required>
            </div>
            <div>
                <input class="btn btn-outline-dark w-100 p-2 fw-bold" type="submit" value="Sign up">
            </div>
        </form>
        <div class="mt-3">
            <p class="text-center">Already have an account? <a href="{% url 'login' %}">Login now!</a></p>
        </div>
    </div>
</div>
{% endblock %}

users/templates/update_profile.html
<!-- profile_update.html -->
{% extends 'base.html' %}
{% load static %}
{% block head_title %}Update Profile{% endblock %}
{% block content %}
<div class="form d-flex justify-content-center align-items-center my-3">
    <div class="d-flex flex-column justify-content-center p-5 rounded rounded shadow-lg" style="width: 640px; background: #e9e8e8;">
        <div class="text-center fw-bold mb-5 fs-1">
            <h3>Update your profile</h3>
        </div>
        <form enctype="multipart/form-data" action="" method="POST">
            {% csrf_token %}            
            <!-- fruit Name -->
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                <strong>Error!</strong> Please correct the following errors:
                <ul>
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <li>{{ field }}:{{ error }}</li>
                    {% endfor %}
                {% endfor %}
                </ul>
            </div>
            {% endif %}
            
            <div class="d-flex justify-content-between">
                <div style="width: 47.5%;">
                    <div>
                        {% if form.instance.account.profile_image %}
                        <img id="previewImage" class="uploaded-image center-image" src="{{ form.instance.account.profile_image.url }}" alt="Preview Image">
                        {% else %}
                        <img id="previewImage" class="uploaded-image center-image" src="{% static './images/profile.png' %}" alt="Preview Image">
                        {% endif %}
                    </div>
                    <div class="input-box">
                        <div class="input-box">
                            <label for="uploadImage">Profile Image:</label>
                            <input type="file" id="uploadImage" class="input-field" name="profile_image" onchange="displayImage()">
                            <label class="up-image-label overflow-auto" for="uploadImage">
                                {% if form.instance.account.profile_image %}
                                <span class="image-label "><i class="fa-solid fa-upload me-2"></i>{{ form.instance.account.profile_image.name }}</span>
                                {% else %}
                                <span class="image-label "><i class="fa-solid fa-upload me-2"></i>Upload proofile image</span>
                                {% endif %}
                            </label>
                        </div>
                    </div>
                </div>
                <div style="width: 47.5%;">
                    <div class="input-box">
                        <label for="id_first_name">First Name:</label>
                        <input type="text" id="id_first_name" class="input-field" placeholder="Enter your first name" name="first_name" autocomplete="off" required value="{{ form.instance.first_name }}">
                    </div>
                    <div class="input-box">
                        <label for="id_last_name">Last Name:</label>
                        <input type="text" id="id_last_name" class="input-field" placeholder="Enter your last name" name="last_name" autocomplete="off" required value="{{ form.instance.last_name }}">
                    </div>
                    <div class="input-box">
                        <label for="id_gender">Gender:</label>
                        <select id="id_gender" class="input-field" name="gender" required>
                            <option class="text-secondary" hidden>Select your gender</option>
                            <option value="Male" {% if form.instance.account.gender == "Male" %} selected {% endif %}>Male</option>
                            <option value="Female" {% if form.instance.account.gender == "Female" %} selected {% endif %}>Female</option>
                        </select>
                    </div>
                </div>
            </div>
        
            <!-- Email -->
            <div class="input-box">
                <label for="id_email">Email:</label>
                <input type="email" id="id_email" class="input-field" placeholder="Enter your email" name="email" autocomplete="off" required value="{{ form.instance.email }}">
            </div>
            <!-- Gender -->
            
            <!-- Save and Update Password Buttons -->
            <div class="d-flex justify-content-between mt-4">
                <div style="width: 47.5%;">
                    <input class="btn btn-outline-dark w-100 p-2 fw-bold" type="submit" value="Save">
                </div>
                <div style="width: 47.5%;">
                    <a class="btn btn-outline-danger w-100 p-2 fw-bold text-decoration-none" href="{% url 'change_pass' %}">Update Password</a>
                </div>
            </div>
        </form>
    </div>
</div>

{% if form.instance.account.profile_image %}
<script>
    const imageUrl = "{{ form.instance.account.profile_image }}";
    const fileName = imageUrl.substring(imageUrl.lastIndexOf('/') + 1);
    document.querySelector('.image-label').textContent = fileName;
</script>
{% endif %}

{% endblock %}