core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
]

fruit/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.available_fruits, name='fruits'),
    path('fruit_details/<int:id>/', views.DetailFruitView.as_view(), name='details'),

    path('add_fruit', views.add_fruit, name='add_fruit'),
    path('edit_fruit/<int:id>/', views.EditFruitView.as_view(), name='edit_fruit'),
    path('add_vendor', views.add_vendor, name='add_vendor'),

    path('stocked_out/<int:id>/', views.make_stocked_out, name='stocked_out'),
    path('archive_fruits/', views.archive_fruits, name='archive'),
    path('move_to_regular/<int:id>/', views.move_to_regular, name='move_to_regular'),
    path('remove_fruit/<int:id>/', views.remove_fruit, name='remove_fruit'),

    path('flash_sale/<int:id>/', views.add_to_flash_sale, name='flash_sale'),
    path('flash_sale/', views.flash_sale_fruits, name='flash_sale_fruits'),
    path('regular_sale/<int:id>/', views.make_regular_sale, name='regular_sale'),

    path('add_to_wishlist/<int:id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('remove_from_wishlist/<int:id>/', views.remove_from_wishlist, name='remove_from_wishlist'),

    
]

fruit_sell/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("core.urls")),
    path('fruits/',include("fruit.urls")),
    path('user/', include('users.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fruit/models.py
from django.db import models
from django.contrib.auth.models import User
from users.models import UserAccount
from blockchain import add_fruit

# Create your models here.
class Vendor(models.Model):
    vendor_name = models.CharField(max_length=100)
    NID_number = models.CharField(max_length=17)
    phone_number = models.CharField(max_length=14)
    address = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.vendor_name}"
class FruitModel(models.Model):
    blockchain_id = models.CharField(max_length=100, blank=True, null=True)
    name=models.CharField(max_length=100)
    image=models.ImageField(upload_to='./fruit-images/', blank=True, null=True)
    description=models.TextField()
    location=models.CharField(max_length=100)
    vendor=models.ForeignKey(Vendor, on_delete=models.CASCADE, blank=True, null=True)
    supply_date=models.DateField(blank=True, null=True)
    expiry_date=models.DateField(blank=True, null=True)
    price=models.DecimalField(max_digits=8, decimal_places=2)
    unit=models.CharField(max_length=100, blank=True, null=True)
    discount=models.DecimalField(max_digits=8, decimal_places=2,default=0)
    stocked_out = models.BooleanField(default=False)
    flash_sale = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.name} from {self.location}"
    
    def get_discounted_price(self):
        if self.discount > 0:
            discount_amount = (self.price * self.discount) / 100
            discounted_price = self.price - discount_amount
            return format(discounted_price, "0.2f")
        else:
            return self.price
        
    def save_to_blockchain(self):
        try:
            receipt = add_fruit(
                self.name,
                self.location,
                str(self.supply_date),
                str(self.expiry_date),
                self.vendor.vendor_name,
                self.description,  # Assuming description is used as trace_info
                self.id
            )
            self.blockchain_id = receipt['transactionHash'].hex()
            self.save()
            # print(f"Blockchain ID saved: {self.blockchain_id}")
        except Exception as e:
            print(f"Error saving to blockchain: {e}")
            raise

class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fruit = models.ForeignKey(FruitModel, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username} looking for: {self.fruit.name}"
   
class Comment(models.Model):
    post = models.ForeignKey(FruitModel, on_delete=models.CASCADE, related_name='comments')
    name = models.ForeignKey(UserAccount, on_delete=models.CASCADE)
    review = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='./review-images/uploads/', blank=True, null=True)
    rate = models.IntegerField(default=0)

    def __str__(self):
        return f"Review by {self.name}"

fruit/forms.py
from django import forms
from .models import FruitModel, Vendor, Comment

class FruitForm(forms.ModelForm):
    class Meta:
        model=FruitModel
        fields= '__all__'

class VendorForm(forms.ModelForm):
    class Meta:
        model = Vendor
        fields= '__all__'

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['image', 'review', 'rate']
        widgets = {
            'review': forms.Textarea(attrs={'rows': 3, 'placeholder': 'Enter Your review here'}),
            'rate': forms.RadioSelect(choices=[(i, i) for i in range(1, 6)]),
        }

    def clean(self):
        cleaned_data = super().clean()
        review = cleaned_data.get('review')
        rate = cleaned_data.get('rate')

        if not review:
            self.add_error('review', 'This field is required.')
        if not rate:
            self.add_error('rate', 'This field is required.')

        return cleaned_data

fruit/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.views import View
from django.views.generic import DetailView
from fruit.models import FruitModel, Vendor, Wishlist, Comment
from django.contrib import messages
from .forms import FruitForm, VendorForm, CommentForm
from order.models import Order
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from blockchain import get_fruit
from django.core.paginator import Paginator

# Create your views here.
def available_fruits(request):
    p = Paginator(FruitModel.objects.filter(stocked_out=False),9)
    page = request.GET.get('page')
    data = p.get_page(page)
    return render(request, 'fruits.html', {'data':data })

class DetailFruitView(DetailView):
    model = FruitModel
    pk_url_kwarg = 'id'
    template_name = 'fruit_details.html'

    def post(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            return self.get(request, *args, **kwargs)
         
        comment_form = CommentForm(request.POST, request.FILES)
        post = self.get_object()
        user_account = request.user.account

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.name = user_account
            comment.post = post
            comment.save()
            messages.success(request, 'Thank you for your review!')
        else:
            messages.warning(request, 'Error! Review not saved.')
            print(comment_form.errors)  # For debugging

        referer_url = request.META.get('HTTP_REFERER', '/')
        return HttpResponseRedirect(referer_url)

    def reviewer(self, user, fruit):
        if not user.is_authenticated:
            return False
        delivered_orders = Order.objects.filter(user=user, order_status='Delivered', ordered=True)
        for order in delivered_orders:
            if order.order_items.filter(item=fruit).exists():
                return True
        return False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        post = self.object
        comments = post.comments.all().order_by('-created_on')
        comment_form = CommentForm()
        can_review = self.reviewer(user, post)
        context['comments'] = comments
        context['comment_form'] = comment_form
        context['can_review'] = can_review
        if post.blockchain_id:
            try:
                blockchain_data = get_fruit(post.id)
                # Add debugging prints
                # print(f"Blockchain data for fruit ID {post.id}: {blockchain_data}")
                context['blockchain_data'] = blockchain_data
            except Exception as e:
                print(f"Error fetching blockchain data: {e}")
                context['blockchain_data'] = None
        return context

@login_required
def add_fruit(request):
    if request.method == 'POST':
        fruit_form = FruitForm(request.POST, request.FILES)

        if fruit_form.is_valid():
            name = fruit_form.cleaned_data.get("name")
            image = fruit_form.cleaned_data.get("image")
            description = fruit_form.cleaned_data.get("description")
            location = fruit_form.cleaned_data.get("location")
            vendor = fruit_form.cleaned_data.get("vendor")
            supply_date = fruit_form.cleaned_data.get("supply_date")
            expiry_date = fruit_form.cleaned_data.get("expiry_date")
            unit = fruit_form.cleaned_data.get("unit")
            price = fruit_form.cleaned_data.get("price")
            discount = fruit_form.cleaned_data.get("discount")
            new_fruit = FruitModel.objects.create(
                name=name,
                description=description,
                location=location,
                supply_date=supply_date,
                expiry_date=expiry_date,
                unit=unit,
                price=price,
                image=image,
                vendor=vendor,
                discount=discount
            )
            try:
                new_fruit.save_to_blockchain()
                messages.success(request, 'New fruit added and saved to blockchain successfully!')
            except Exception as e:
                messages.warning(request, f"Error adding fruit to blockchain: {e}")
            # messages.success(request, 'New fruit added successfully!')
            return redirect('fruits')
    else:
        fruit_form = FruitForm()

        return render(request, 'add_fruit.html', {'form': fruit_form})
    return render(request, 'add_fruit.html', {'form': fruit_form})

@method_decorator(login_required, name='dispatch')
class EditFruitView(View):
    template_name = 'edit_fruit.html'
    pk_url_kwarg = 'id'

    def get(self, request, *args, **kwargs):
        fruit_id = kwargs.get(self.pk_url_kwarg)
        fruit_instance = get_object_or_404(FruitModel, id=fruit_id)
        form = FruitForm(instance=fruit_instance)
        return render(request, self.template_name, {'form': form, 'fruit_instance': fruit_instance})

    def post(self, request, *args, **kwargs):
        fruit_id = kwargs.get(self.pk_url_kwarg)
        fruit_instance = get_object_or_404(FruitModel, id=fruit_id)
        blockchain_id = fruit_instance.blockchain_id
        form = FruitForm(request.POST, request.FILES, instance=fruit_instance)
        if form.is_valid():
            fruit_instance = form.save(commit=False)
            fruit_instance.blockchain_id = blockchain_id
            fruit_instance.save()
            messages.success(self.request, 'Fruit post updated successfully!')
            referer_url = request.META.get('HTTP_REFERER', '/')
            return HttpResponseRedirect(referer_url)
        return render(request, self.template_name, {'form': form})

@login_required
def add_vendor(request):
    vendor_form = VendorForm()
    if request.method == 'POST':
        vendor_form = VendorForm(request.POST, request.FILES)
        if vendor_form.is_valid():
            vendor_name = vendor_form.cleaned_data.get("vendor_name")
            NID_number = vendor_form.cleaned_data.get("NID_number")
            phone_number = vendor_form.cleaned_data.get("phone_number")
            address = vendor_form.cleaned_data.get("address")

            Vendor.objects.create(
                vendor_name=vendor_name,
                NID_number=NID_number,
                phone_number=phone_number,
                address=address,
            )
            messages.success(request, 'New vendor added successfully. Add more vendor!')
            return redirect('add_vendor')
        else:
            return render(request, 'add_vendor.html', {'form': vendor_form })
    return render(request, 'add_vendor.html', {'form': vendor_form })

@login_required
def make_stocked_out(request, id):
    fruit = get_object_or_404(FruitModel, id=id)
    fruit.stocked_out = True
    fruit.flash_sale = False
    fruit.save()
    messages.success(request, f'{fruit.name} marked as stocked out!')
    referer_url = request.META.get('HTTP_REFERER', '/')
    return HttpResponseRedirect(referer_url)

@login_required
def archive_fruits(request):
    data = FruitModel.objects.filter(stocked_out=True)
    return render(request, 'archive_fruits.html', {'data':data})

@login_required
def move_to_regular(request, id):
    fruit = get_object_or_404(FruitModel, id=id)
    fruit.stocked_out = False
    fruit.save()
    messages.success(request, f'{fruit.name} added in stocks!')
    referer_url = request.META.get('HTTP_REFERER', '/')
    return HttpResponseRedirect(referer_url)

@login_required
def remove_fruit(request, id):
    fruit = get_object_or_404(FruitModel, id=id)
    messages.success(request, f'{fruit.name} removed successfully!')
    fruit.delete()
    referer_url = request.META.get('HTTP_REFERER', '/')
    return HttpResponseRedirect(referer_url)

@login_required
def add_to_flash_sale(request, id):
    fruit = get_object_or_404(FruitModel, id=id)
    fruit.flash_sale = True
    fruit.save()
    messages.success(request, f'{fruit.name} added to flash sale!')
    referer_url = request.META.get('HTTP_REFERER', '/')
    return HttpResponseRedirect(referer_url)

@login_required
def flash_sale_fruits(request):
    data = FruitModel.objects.filter(flash_sale=True)
    return render(request, 'flash_sale.html', {'data':data})

@login_required
def make_regular_sale(request, id):
    fruit = get_object_or_404(FruitModel, id=id)
    fruit.flash_sale = False
    fruit.save()
    messages.success(request, f'{fruit.name} moved to regular sale!')
    referer_url = request.META.get('HTTP_REFERER', '/')
    return HttpResponseRedirect(referer_url)


@login_required
def add_to_wishlist(request, id):
    fruit = get_object_or_404(FruitModel, id=id)
    Wishlist.objects.get_or_create(user=request.user, fruit=fruit)
    messages.success(request, f'{fruit.name} added to wishlist successfully!')
    referer_url = request.META.get('HTTP_REFERER', '/')
    return HttpResponseRedirect(referer_url)

@login_required
def wishlist(request):
    fruits = Wishlist.objects.filter(user=request.user)
    return render(request, 'wishlist.html', {'fruits': fruits})

@login_required
def remove_from_wishlist(request, id):
    wish_fruit = get_object_or_404(Wishlist, id=id, user=request.user)
    messages.success(request, f'{wish_fruit.fruit.name} removed from wishlist successfully!')
    wish_fruit.delete()
    referer_url = request.META.get('HTTP_REFERER', '/')
    return HttpResponseRedirect(referer_url)

fruit/templates/add_fruit.html
{% extends 'base.html' %}
{% block head_title %}Add Fruits{% endblock %}
{% load static %}
{% block content %}
<div class="form d-flex justify-content-center align-items-center my-3">
    <div class="d-flex flex-column justify-content-center p-4 rounded rounded shadow-lg" style="width: 640px;  background: #e9e8e8;">
        <div class="text-center fw-bold mb-3 fs-1">
            <h3 class="text-center fw-bold ">Add Fruit</h3>
        </div>
        <form enctype="multipart/form-data" action="" method="POST">
            {% csrf_token %}            
            <!-- fruit Name -->
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                <strong>Error!</strong> Please correct the following errors:
                <ul>
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <li>{{ field }}:{{ error }}</li>
                    {% endfor %}
                {% endfor %}
                </ul>
            </div>
            {% endif %}
            <div class="d-flex justify-content-between">
                <div style="width: 47.5%;">
                    <div>
                        <img id="previewImage" class="uploaded-image center-image" src="{% static './images/up.png' %}" alt="Preview Image" >
                    </div>
                    <div class="input-box">
                        <div class="input-box">
                            <label for="uploadImage">Fruit Image:</label>
                            <input type="file" id="uploadImage" class="input-field" name="image" onchange="displayImage()">
                            <label class="up-image-label overflow-hidden" for="uploadImage">
                                <i class="fa-solid fa-upload me-2"></i>
                                <span class="image-label ">Upload fruit image</span>
                            </label>
                        </div>
                    </div>
                </div>
                <div style="width: 47.5%;">
                    <div class="input-box">
                        <label for="id_name">Fruit name:</label>
                        <input type="text" id="id_name" class="input-field" placeholder="Enter fruit name" name="name" autocomplete="off" >
                    </div>
                    <div class="input-box">
                        <label for="id_location">Fruit from:</label>
                        <input type="text" id="id_location" class="input-field" placeholder="Enter fruit location" name="location" autocomplete="off" >
                    </div>
                    <div class="input-box">
                        <label for="id_vendor">Vendor:</label>
                        {{ form.vendor }}
                    </div>
                </div>
            </div>
            <!-- Description -->
            <div class="d-flex justify-content-between">
                <div style="width: 47.5%;" class="input-box">
                    <label for="id_description">Fruit description:</label>
                    <textarea rows="4" id="id_description" class="textarea-field" placeholder="Enter fruit description" name="description"></textarea>
                </div>
                <div style="width: 47.5%;">
                    <div class="input-box">
                        <label class="d-inline" for="id_supply_date">Supply date:</label>
                        <input type="date" id="id_supply_date" class="input-field" value="{{ fruit_instance.supply_date|date:'Y-m-d' }}" name="supply_date">
                    </div>
                    <div class="input-box">
                        <label for="id_expiry_date">Expiry date:</label>
                        <input type="date" id="id_expiry_date" class="input-field" name="expiry_date">
                    </div>
                </div>
            </div>

            <div class="d-flex justify-content-between gap-3">
                
                <div class="input-box">
                    <label for="id_unit">Quantity-Unit:</label>
                    <input type="text" id="id_unit" class="input-field" placeholder="Enter quantity with unit" name="unit" >
                </div>
                <div class="input-box">
                    <label for="id_price">Price per unit:</label>
                    <input type="number" id="id_price" class="input-field" placeholder="Enter price" name="price" >
                </div>
                <div class="input-box">
                    <label for="id_discount">Discount:</label>
                    <input type="number" id="id_discount" class="input-field" placeholder="Enter discount" name="discount">
                </div>
                
            </div>
            <div class="my-2">
                <input class="btn btn-outline-dark w-100 p-2 fw-bold" type="submit" value="Add">
            </div>
        </form>
    </div>
</div>
<script>
     document.addEventListener('DOMContentLoaded', function() {
        var vendorField = document.getElementById('id_vendor');
        vendorField.classList.add('input-field');
    });
</script>
{% endblock %}

fruit/templates/add_vendor.html
{% extends 'base.html' %}
{% block head_title %}Add Vendor{% endblock %}
{% block content %}
<div class="form d-flex justify-content-center align-items-center my-3">
    <div class="d-flex flex-column justify-content-center p-5 rounded rounded shadow-lg"
        style="width: 640px;  background: #e9e8e8;">
        <div class="mb-3 fs-1">
            <h3 class="text-center fw-bold ">Add New Vendor</h3>
        </div>
        <form enctype="multipart/form-data" action="" method="POST">
            {% csrf_token %}
            <!-- fruit Name -->
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                <strong>Error!</strong> Please correct the following errors:
                <ul>
                    {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                    <li>{{ field }}:{{ error }}</li>
                    {% endfor %}
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

            <div class="d-flex justify-content-between">
                <div style="width: 47.5%;" class="input-box">
                    <label for="id_vendor_name">Name:</label>
                    <input type="text" id="id_vendor_name" class="input-field" placeholder="Enter vendor name"
                        name="vendor_name" autocomplete="off">
                </div>
                <div style="width: 47.5%;" class="input-box">
                    <label for="id_NID_number">NID number:</label>
                    <input type="text" id="id_NID_number" class="input-field" placeholder="Enter vendor's NID"
                        name="NID_number" autocomplete="off">
                </div>
            </div>
            <div class="d-flex justify-content-between">
                <div style="width: 47.5%;" class="input-box">
                    <label for="id_phone_number">Phone number:</label>
                    <input type="text" id="id_phone_number" class="input-field" placeholder="Enter vendor's phone"
                        name="phone_number" autocomplete="off">
                </div>
                <div style="width: 47.5%;" class="input-box">
                    <label for="id_address">Address:</label>
                    <input type="text" id="id_address" class="input-field" placeholder="Enter vendor's address"
                        name="address" autocomplete="off">
                </div>
            </div>


            <div class="my-3">
                <input class="btn btn-outline-dark w-100 p-2 fw-bold" type="submit" value="Add">
            </div>
        </form>
    </div>
</div>
{% endblock %}

fruit/templates/edit_fruit.html
{% extends 'base.html' %}
{% block head_title %}Edit Fruit{% endblock %}
{% load static %}
{% block content %}
<div class="form d-flex justify-content-center align-items-center my-3">
    <div class="d-flex flex-column justify-content-center p-4 rounded rounded shadow-lg" style="width: 640px;  background: #e9e8e8;">
        <div class="text-center fw-bold mb-3 fs-3">
            <header>Edit Fruit</header>
        </div>
        <form enctype="multipart/form-data" action="" method="POST">
            {% csrf_token %}            
            <!-- fruit Name -->
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                <strong>Error!</strong> Please correct the following errors:
                <ul>
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <li>{{ field }}:{{ error }}</li>
                    {% endfor %}
                {% endfor %}
                </ul>
            </div>
            {% endif %}
            
            <div class="d-flex justify-content-between">
                <div style="width: 47.5%;">
                    <div>
                        {% if form.instance.image %}
                        <img id="previewImage" class="uploaded-image center-image" src="{{ form.instance.image.url }}" alt="Preview Image">
                        {% else %}
                        <img id="previewImage" class="uploaded-image center-image" src="{% static './images/No-Image-Placeholder.svg' %}" alt="Preview Image">
                        {% endif %}
                    </div>
                    <div class="input-box">
                        <div class="input-box">
                            <label for="uploadImage">Fruit Image:</label>
                            <input type="file" id="uploadImage" class="input-field" name="image" onchange="displayImage()">
                            <label class="up-image-label overflow-auto" for="uploadImage">
                                <i class="fa-solid fa-upload me-2"></i>
                                {% if form.instance.image %}
                                <span class="image-label ">{{ form.instance.image.name }}</span>
                                {% else %}
                                <span class="image-label ">Upload fruit image</span>
                                {% endif %}
                            </label>
                        </div>
                    </div>
                </div>
                <div style="width: 47.5%;">
                    <div class="input-box">
                        <label for="id_name">Fruit name:</label>
                        <input type="text" id="id_name" class="input-field" placeholder="Enter fruit name" value="{{ form.instance.name }}" name="name" autocomplete="off" >
                    </div>
                    <div class="input-box">
                        <label for="id_location">Fruit from:</label>
                        <input type="text" id="id_location" class="input-field" placeholder="Enter fruit location" value="{{ form.instance.location }}" name="location" autocomplete="off" >
                    </div>
                    <div class="input-box">
                        <label for="id_vendor">Vendor:</label>
                        {{ form.vendor }}
                    </div>
                </div>
            </div>
            <!-- Description -->
            <div class="d-flex justify-content-between">
                <div style="width: 47.5%;" class="input-box">
                    <label for="id_description">Fruit description:</label>
                    <textarea rows="4" id="id_description" class="textarea-field" placeholder="Enter fruit description" name="description">{{ form.instance.description }}</textarea>
                </div>
                <div style="width: 47.5%;">
                    <div class="input-box">
                        <label class="d-inline" for="id_supply_date">Supply date:</label>
                        <input type="date" id="id_supply_date" class="input-field" value="{{ fruit_instance.supply_date|date:'Y-m-d' }}" name="supply_date"  >
                    </div>
                    <div class="input-box">
                        <label for="id_expiry_date">Expiry date:</label>
                        <input type="date" id="id_expiry_date" class="input-field" value="{{ fruit_instance.expiry_date|date:'Y-m-d' }}" name="expiry_date"  >
                    </div>
                </div>
            </div>

            <div class="d-flex justify-content-between gap-3">
                
                <div class="input-box">
                    <label for="id_unit">Quantity-Unit:</label>
                    <input type="text" id="id_unit" class="input-field" placeholder="Enter unit" value="{{ form.instance.unit }}" name="unit" >
                </div>
                <div class="input-box">
                    <label for="id_price">Price per unit:</label>
                    <input type="number" id="id_price" class="input-field" placeholder="Enter price" value="{{ form.instance.price }}" name="price" >
                </div>
                <div class="input-box">
                    <label for="id_discount">Discount:</label>
                    <input type="number" id="id_discount" class="input-field" placeholder="Enter discount" value="{{ form.instance.discount }}" name="discount" >
                </div>
                
            </div>
            <div class="my-3">
                <input class="btn btn-outline-dark w-100 p-2 fw-bold" type="submit" value="Save">
            </div>
        </form>
    </div>
</div>
<script>
     document.addEventListener('DOMContentLoaded', function() {
        var vendorField = document.getElementById('id_vendor');
        vendorField.classList.add('input-field');
    });
    
</script>
{% if form.instance.image %}
<script>
    const imageUrl = "{{ form.instance.image }}";
    const fileName = imageUrl.substring(imageUrl.lastIndexOf('/') + 1);
    document.querySelector('.image-label').textContent = fileName;
</script>
{% endif %}
{% endblock %}