core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
]

fruit_sell/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("core.urls")),
    path('fruits/',include("fruit.urls")),
    path('user/', include('users.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label="Write your full Name ",required=True,  widget = forms.TextInput(attrs={'class': 'form-control', 'id':'text-area', 'placeholder':'Enter your full name'}))
    email = forms.EmailField(label="Write your email",required=False, widget = forms.TextInput(attrs={'class': 'form-control', 'id':'text-area', 'placeholder':'Enter your email'}))
    feedback = forms.CharField(label="Write your feedback ",required=True, widget = forms.Textarea(attrs={'class': 'form-control', 'id':'text-area', 'placeholder':'Write your feedback'}))

         

core/views.py
from django.shortcuts import render, redirect
from fruit.models import FruitModel
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from django.contrib import messages
from .forms import ContactForm

# Create your views here.
def home(request):
    data = FruitModel.objects.filter(flash_sale=False).order_by("?")
    flashsale = FruitModel.objects.filter(flash_sale=True)
    return render(request, 'home.html', {'data':data, 'flashsale':flashsale })

def send_email(user, email_to, subject, template):
        message = render_to_string(template, {
            'user' : user,
        })
        send_email = EmailMultiAlternatives(subject, '', to=[email_to])
        send_email.attach_alternative(message, "text/html")
        send_email.send()

def send_contact_email(name, email, feedback):
        message = render_to_string("contact_mail.html", {
            'name' : name,
            'email' : email,
            'feedback' : feedback,
        })
        send_email = EmailMultiAlternatives('Feedback mail from Fruitchain', '', to=["mahadimunna.official@gmail.com"])
        send_email.attach_alternative(message, "text/html")
        send_email.send()

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            feedback = form.cleaned_data['feedback']
            send_contact_email(name, email, feedback)
            messages.success(request,'Your message successfully send! Thank you for contacting us.')
            return redirect('home')
    else:
        form = ContactForm()
    return render(request, 'contact.html',{'form':form})

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="Ecommerce System" />
    <title>{% block head_title %}Home{% endblock %}-Fruit Chain</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <link rel="shortcut icon" href="{% static 'img/logo.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}" />
    <script
      src="https://kit.fontawesome.com/581cc1dd1f.js"
      crossorigin="anonymous"
    ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <link
      rel="stylesheet"
      href="//cdn.jsdelivr.net/npm/alertifyjs@1.14.0/build/css/alertify.min.css"
    />
    <link
      rel="stylesheet"
      href="//cdn.jsdelivr.net/npm/alertifyjs@1.14.0/build/css/themes/default.min.css"
    />

    {% block head_link %} {% endblock %}
  </head>

  <body>
    <div class="d-flex">
      <div style="width: 12%">{% include 'navbar.html' %}</div>
      <div style="width: 88%">
        {% block body %}
        <div class="lg:container lg:mx-auto" id="main">
          {% block content %} {% endblock %}
        </div>
        {% endblock %}
      </div>
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>

    <script src="{% static 'script/script.js' %}"></script>
    <script src="{% static 'script/owl.carousel.min.js' %}"></script>

    <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.14.0/build/alertify.min.js"></script>
    <script>
              alertify.set('notifier','position', 'top-left');
              {% if messages %}
                {% for message in messages %}
                {% if message.tags == "warning" %}
                alertify.warning('{{message|safe}}');
                {% else %}
                alertify.success('{{message|safe}}');
                {% endif %}
                {% endfor %}
                {% endif %}
    </script>
    {% block scripts %} {% endblock %}
  </body>
</html>

core/templates/contact.html
{% extends 'base.html' %}

{% block head_title %}Contact{% endblock %}

{% block content %}
{% load static %}

<div class="d-flex justify-content-between container mt-2" >
    <div style="width: 47.5%;" class="container d-flex flex-column justify-content-center align-items-center my-3">
        <img style="width: 300px;" class="rounded rounded-5 me-md-5" src="{% static 'img/Munna.jpg' %}" alt="">
        <div style="max-width: 600px;" class="d-flex flex-column justify-content-center mt-3">
            <h2 class="text-center text-success fw-bold">About Developer</h2>
            <h5 class="text-center">Hello, I'm Mahadi Hasan Munna. Here I develop this web
                application. If you need any help or query about this application you can send mail anytime!
            </h5>
            <p class="text-center"><a target="_blank" class="btn btn-primary mt-3" href="https://mahadi-hasan-munna.web.app/">Visit My Portfolio</a></p>
        </div>
    </div>
    <div class="d-flex flex-column justify-content-center p-5 rounded rounded shadow-lg" style="width: 47.5%;; background: #e0dddd;">
        <div class="text-center fw-bold mb-5 fs-1">
            <header>Send your message!</header>
        </div>
        <form style="width: 440px;" class="mx-auto" enctype="multipart/form-data" action="" method="post">
            {% csrf_token %}
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                <strong>Error!</strong> Please correct the following errors:
                <ul>
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <li>{{ field }}: {{ error }}</li>
                    {% endfor %}
                {% endfor %}
                </ul>
            </div>
            {% endif %}
            <!-- name -->
            <div class="input-box">
                <label for="id_name">Name:</label>
                <input type="text" id="id_username" class="input-field" placeholder="Enter your full name" name="name" autocomplete="off" required>
            </div>
            <!-- email -->
            <div class="input-box">
                <label for="id_email">Email:</label>
                <input type="email" id="id_email" class="input-field" placeholder="Enter your email" name="email" autocomplete="off" required>
            </div>
            <!-- feedback -->
            <div class="input-box">
                <label for="id_feedback">Message:</label>
                <textarea rows="4" id="id_feedback" class="textarea-field" placeholder="Enter your message" name="feedback"></textarea>
            </div>
            
            <!-- Submit Button -->
            <div>
                <input class="btn btn-outline-dark w-100 p-2 fw-bold" type="submit" value="Send">
            </div>
        </form>
    </div>
</div>

{% endblock %}

core/templates/contact_mail.html
<h3>A message from FruitChain</h3>

<p>Name: {{name}}</p>
<p>Email: {{email}}</p>
<p style="margin: 3px,0px,3px,0px;">Message: {{feedback}}</p>

core/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block head_title %}Home{% endblock %}
{% block head_link %}
    <link rel="stylesheet" href="{% static '/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/owl.theme.default.min.css' %}">
{% endblock %}
{% block body %}
{% load static %}

{% if flashsale  %}
<div class="container mx-auto ">
    <h4 class="my-2 rounded text-danger fw-bold">Hot deals</h4>
    <div class="row owl-carousel owl-theme gap-2">
        {% for fruit in flashsale %}
        <div class="item card mb-3" style="width: 350px; height: fit-content; border: none;">
            <div class="row">
                <div class="col-4 d-flex justify-content-center align-items-center">
                    {% if fruit.image %}
                    <img class="card-img" src="{{fruit.image.url}}" class="img-fluid rounded-start" alt="...">
                    {% else %}
                    <img class="card-img" src="{% static './images/No-Image-Placeholder.svg' %}"
                        class="img-fluid rounded-start" alt="...">
                    {% endif %}
                </div>
                <div class="col-8 p-2 ps-0">
                    <div class="card-text">
                        <div class="p-2">
                            <div class="d-flex justify-content-between">
                                <h6 class="card-title">{{fruit.name}}</h6>
                                {% if fruit.stocked_out %}
                                {% else %}
                                {% if fruit.discount > 0 %}
                                <small class="text-danger fw-bold"> -{{ fruit.discount }}% </small>
                                {% endif %}
                                {% endif %}
                            </div>
                            <small class="card-text ">{{fruit.description | truncatewords:6}} <a
                                    class="text-decoration-none"
                                    href="{% url 'details' id=fruit.id %}">view</a></small><br>
                            {% if fruit.stocked_out %}
                            <small class="fw-bold"><s>{{fruit.price}}৳</s><span class="fw-bold text-danger ms-2">Stocked
                                    out</span></small>
                            {% else %}
                            {% if fruit.discount > 0 %}
                            <small class="fw-bold"><s>{{fruit.price}}৳</s> <span
                                    class="text-danger">{{fruit.get_discounted_price}}৳ per {{fruit.unit}}</span> </small><br>
                            {% else %}
                            <small class="fw-bold">{{fruit.price}}৳ per {{fruit.unit}}</small><br>
                            {% endif %}
                            {% endif %}

                            {% if request.user.is_staff %}
                            <div class="mt-2">
                                <a class="card-btn btn btn-dark" href="{% url 'edit_fruit' id=fruit.id %}">Edit Post</a>
                                <a class="card-btn btn btn-dark" href="{% url 'regular_sale' fruit.id %}">Make Regular Sale</a>
                                {% if fruit.stocked_out %}
                                {% else %}
                                <a class="card-btn btn btn-dark" href="{% url 'stocked_out' fruit.id %}">Make stock
                                    Out</a>
                                {% endif %}
                                <a class="card-btn btn btn-dark" href="{% url 'remove_fruit' fruit.id %}">Delete fruit</a>
                            </div>
                            {% else %}
                            {% if fruit.stocked_out %}
                            <div class="d-flex justify-content-between align-items-center mt-2">
                                <a class="card-btn btn btn-dark" href="{% url 'add_to_wishlist' fruit.id %}">Add to
                                    wishlist</a>
                            </div>
                            {% else %}
                            <div class="d-flex justify-content-between align-items-center mt-2">
                                <a class="card-btn btn btn-dark" href="{% url 'add_to_wishlist' fruit.id %}">Add to
                                    wishlist</a>
                                <a class="card-btn btn btn-dark" href="{% url 'add-to-cart' fruit.id %}">Add to Cart</a>
                            </div>
                            {% endif %}

                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% endfor %}

    </div>
</div>
{% endif %}
<div class="container mx-auto ">
    <h4 class="my-2 rounded text-success fw-bold">Get more fresh Fruits from here</h4>
    <div class="row ">


        {% for fruit in data|slice:":6" %}

        <div class="card mb-3" style="width: 373px; height: fit-content; border: none;">
            <div class="row">
                <div class="col-4 d-flex justify-content-center align-items-center">
                    {% if fruit.image %}
                    <img class="card-img" src="{{fruit.image.url}}" class="img-fluid rounded-start" alt="...">
                    {% else %}
                    <img class="card-img" src="{% static './images/No-Image-Placeholder.svg' %}"
                        class="img-fluid rounded-start" alt="...">
                    {% endif %}
                </div>
                <div class="col-8 p-2 ps-0">
                    <div class="card-text">
                        <div class="p-2">
                            <div class="d-flex justify-content-between">
                                <h6 class="card-title">{{fruit.name}}</h6>
                                {% if fruit.stocked_out %}
                                {% else %}
                                {% if fruit.discount > 0 %}
                                <small class="text-danger fw-bold"> -{{ fruit.discount }}% </small>
                                {% endif %}
                                {% endif %}
                            </div>
                            <small class="card-text ">{{fruit.description | truncatewords:6}} <a
                                    class="text-decoration-none"
                                    href="{% url 'details' id=fruit.id %}">view</a></small><br>
                            {% if fruit.stocked_out %}
                            <small class="fw-bold"><s>{{fruit.price}}৳</s><span class="fw-bold text-danger ms-2">Stocked
                                    out</span></small>
                            {% else %}
                            {% if fruit.discount > 0 %}
                            <small class="fw-bold"><s>{{fruit.price}}৳</s> <span
                                    class="text-danger">{{fruit.get_discounted_price}}৳ per {{fruit.unit}}</span> </small><br>
                            {% else %}
                            <small class="fw-bold">{{fruit.price}}৳ per {{fruit.unit}}</small><br>
                            {% endif %}
                            {% endif %}

                            {% if request.user.is_staff %}
                            <div class="mt-2">
                                <a class="card-btn btn btn-dark" href="{% url 'edit_fruit' id=fruit.id %}">Edit Post</a>
                                <a class="card-btn btn btn-dark" href="{% url 'flash_sale' fruit.id %}">Add to
                                    Flashsell</a>
                                {% if fruit.stocked_out %}
                                {% else %}
                                <a class="card-btn btn btn-dark" href="{% url 'stocked_out' fruit.id %}">Make stock
                                    Out</a>
                                {% endif %}
                                <a class="card-btn btn btn-dark" href="{% url 'remove_fruit' fruit.id %}">Delete fruit</a>
                            </div>
                            {% else %}
                            {% if fruit.stocked_out %}
                            <div class="d-flex justify-content-between align-items-center mt-2">
                                <a class="card-btn btn btn-dark" href="{% url 'add_to_wishlist' fruit.id %}">Add to
                                    wishlist</a>
                            </div>
                            {% else %}
                            <div class="d-flex justify-content-between align-items-center mt-2">
                                <a class="card-btn btn btn-dark" href="{% url 'add_to_wishlist' fruit.id %}">Add to
                                    wishlist</a>
                                <a class="card-btn btn btn-dark" href="{% url 'add-to-cart' fruit.id %}">Add to Cart</a>
                            </div>
                            {% endif %}

                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% endfor %}

        <p class="text-center"><a class="btn btn-primary w-50" href="{% url 'fruits' %}">See All Fruits</a></p>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
var owl = $('.owl-carousel');
owl.owlCarousel({
    loop:true,
    nav:false,
    dots:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2
        },            
        960:{
            items:3
        },
        1200:{
            items:3
        }
    }
});
owl.on('mousewheel', '.owl-stage', function (e) {
    if (e.deltaY>0) {
        owl.trigger('next.owl');
    } else {
        owl.trigger('prev.owl');
    }
    e.preventDefault();
});
</script>
{% endblock %}

core/templates/navbar.html
{% load static %}
<nav>
    <div class="d-flex justify-content-center align-items-center mb-5">
        <h5 class="text-center">FruitChain</h5>
    </div>
    <div class="mx-2">
        <ul class="list-unstyled">
            <li {% if request.resolver_match.url_name == 'home' %}class="active"{% endif %}><a href="{% url 'home' %}"><i class="fa-solid fa-house"></i>Home</a></li>
            <li {% if request.resolver_match.url_name == 'fruits' %}class="active"{% endif %}><a href="{% url 'fruits' %}"><i class="fa-solid fa-apple-whole"></i>Fruits</a></li>
            {% if request.user.is_staff %}
            <li {% if request.resolver_match.url_name == 'add_fruit' %}class="active"{% endif %}><a href="{% url 'add_fruit' %}"><i class="fa-solid fa-square-plus"></i>Add Fruit</a></li>
            <li {% if request.resolver_match.url_name == 'add_vendor' %}class="active"{% endif %}><a href="{% url 'add_vendor' %}"><i class="fa-solid fa-user-plus"></i>Add Vendor</a></li>
            <li {% if request.resolver_match.url_name == 'archive' %}class="active"{% endif %}><a href="{% url 'archive' %}"><i class="fa-solid fa-box-archive"></i>Stockout list</a></li>
            <li {% if request.resolver_match.url_name == 'flash_sale_fruits' %}class="active"{% endif %}><a href="{% url 'flash_sale_fruits' %}"><i class="fa-solid fa-fire"></i>Flashsale list</a></li>
            <li {% if request.resolver_match.url_name == 'orders' %}class="active"{% endif %}><a href="{% url 'orders' %}"><i class="fa-solid fa-truck"></i></i>Manage Orders</a></li>
            {% elif request.user.is_authenticated %}
            <li {% if request.resolver_match.url_name == 'cart' or request.resolver_match.url_name == 'checkout' %}class="active"{% endif %}><a href="{% url 'cart' %}"><i class="fa-solid fa-cart-shopping"></i>Cart</a></li>
            <li {% if request.resolver_match.url_name == 'wishlist' %}class="active"{% endif %}><a href="{% url 'wishlist' %}"><i class="fa-solid fa-heart"></i>Wishlist</a></li>
            {% endif %}
            <li {% if request.resolver_match.url_name == 'contact' %}class="active"{% endif %}><a href="{% url 'contact' %}"><i class="fa-solid fa-address-book"></i></i>Contact Us</a></li>
            {% if request.user.is_authenticated %}
            <li style="margin-top: 30%;" {% if request.resolver_match.url_name == 'profile' %}class="active"{% endif %}"><a href="{% url 'profile' %}"><i class="fa-solid fa-user"></i>Profile</a></li>
            <li {% if request.resolver_match.url_name == 'logout' %}class="active"{% endif %}><a href="{% url 'logout' %}"><i class="fa-solid fa-right-from-bracket"></i>Logout</a></li>
            {% else %}
            <li style="margin-top: 30%;" {% if request.resolver_match.url_name == 'signup' %}class="active"{% endif %}"><a href="{% url 'signup' %}"><i class="fa-solid fa-user-plus"></i>Signup</a></li>
            <li {% if request.resolver_match.url_name == 'login' %}class="active"{% endif %}><a href="{% url 'login' %}"><i class="fa-solid fa-right-to-bracket"></i>Login</a></li>
            {% endif %}
        </ul>
    </div>
    
    
    
    
    
</nav>